spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbtest01
    username: root
    password: 87632190wh
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: off
  mvc:
    view:
      prefix: /static/html
      suffix: .html
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
  address: 0.0.0.0